Role:
  Type: 'AWS::IAM:Role'
  Properties:
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Principal:
          Service:
          - 'ec2.amazonaws.com'
        Action:
        - 'sts.AssumeRole'
      Policies:
      - PolicyName: ec2
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: Stmt1425388787000
            Effect: Allow
            Action:
            - 'ec2:StopInstance'
            Resource:
            - '*'
            Condition:
              StringEquals:
                'ec2:ResourceTag/aws:cloudformation:stack-id': !Ref 'AWS::StackId'